### ISSUE TITLE
Ignore configure file

### ISSUE THREAD

**Issue by vmarchev** [krampstudio/grunt-jsdoc#103]
Hi! I tried to use my config file (that I copied from node_modules/grunt-jsdoc/node_modules/ink-docstrap/template/jsdoc.conf.json) and tried to replace systemName,  for example. 

I've created myconf.json at the root of my project and configured a task 

`
>      jsdoc: {
>            app: {
>                src: [...],
>                options: {
>                    destination: 'jsdocs',
>                    template: "node_modules/grunt-jsdoc/node_modules/ink-docstrap/template",
>                    configure: "myconf.json" //or ./myconf.json
>              }
>            }
>        }
`

When I run the task, the result seems to be as I didn't put the 'configure' option at all.
I had no errors during the task execution and in debug mode I saw, that file is exists and is valid (you have this check in code). 
And one more thing: I tried placing the string "node_modules/grunt-jsdoc/node_modules/ink-docstrap/template/jsdoc.conf.json" in configure value all is working indeed and the report is customized as expected, but when I use my custom file (copied from jsdoc.conf.json in node_modules to the root of my project) nothing works.
What do I do wrong?

**Comment by avishayhajbi** [comment]
it happen to me too.
when i exec :
./node_modules/.bin/jsdoc .\controllers .\index.js --readme .\README.md
it WORK but...
require('./node_modules/jsdoc/jsdoc')
module.exports = function(grunt) {
	// 'use-strict'
    grunt.initConfig({
    	// pkg: grunt.file.readJSON('package.json'),
    	jsdoc : {
	        dist : {
	            src: ['controllers/*.js','index.js','README.md'],
	            options: {
	                destination: 'jsdoc',
	                template : "./node_modules/grunt-jsdoc/node_modules/ink-docstrap/template",
	                configure : "./node_modules/grunt-jsdoc/node_modules/ink-docstrap/template/jsdoc.conf.json"
	            }
	        }
	      }
    });

    // Call these here instead, where the variable grunt is defined.
    grunt.loadNpmTasks('grunt-jsdoc');

    grunt.registerTask('default', ['lint','test','jsdoc']);
};

this is not! i have no errors and the out folder created only with the date time.
it ignored from the 'dist' in the config ..
how to fix it ?
