### ISSUE TITLE
'grunt-retire' complaining about latest version of grunt-jsdoc 0.5.7

### ISSUE THREAD

**Issue by aslamj** [krampstudio/grunt-jsdoc#106]
>> marked 0.2.8 has known vulnerabilities: https://nodesecurity.io/advisories/marked_multiple_content_injection_vulnerabilities
grunt-jsdoc 0.5.7
↳ jsdoc 3.2.2
 ↳ marked 0.2.8

**Comment by krampstudio** [comment]
As jsdoc 3.3.0 is now stable retire doesn't complaint anymore for `marked`
