### ISSUE TITLE
JSdoc output not showing when using --explain

### ISSUE THREAD

**Issue by Risto-Stevcev** [krampstudio/grunt-jsdoc#108]
Grunt won't display the JSdoc output when using the `--explain` flag, but it shows up under `grunt --debug`.

**Gruntfile.js**:
```js
jsdoc : {
  dist : {
    src: ['src/*.js', 'test/*.js'], 
    options: {
      explain: true,
      destination: 'doc'
    }
  }
}
```

Grunt runs without errors, doesn't display the verbose info from `--explain`, and says that documentation is generated (which is not true when I look in the `doc/` folder):
```
$ grunt jsdoc

Running "jsdoc:dist" (jsdoc) task
Documentation generated to $HOME/javascript/yumparse/doc
Done, without errors.

$ ls doc/
$
```

But on debug it *will* show the verbose info from `--explain`:
```bash
$ grunt --debug

[D] Task source: $HOME/git/javascript/yumparse/node_modules/grunt-jsdoc/tasks/jsdoc-plugin.js
[D] { private: true, explain: true, destination: 'doc' }
[D] nodePath
[D] look up node_modules/jsdoc/jsdoc at node_modules/jsdoc/jsdoc
[D] look up node_modules/jsdoc/jsdoc at node_modules/grunt-jsdoc/
[D] look up node_modules/jsdoc/jsdoc at node_modules/grunt-jsdoc/node_modules/jsdoc/jsdoc
[D] jsdoc found at : node_modules/grunt-jsdoc/node_modules/jsdoc/jsdoc
[D] Reading option: private
[D] Reading option: explain
[D] Reading option: destination
[D]                 > doc
[D] Running : node_modules/grunt-jsdoc/node_modules/jsdoc/jsdoc --private --explain --destination doc src/yumparse.js test/yumparse.test.js
...
(** the --explain flag contents does shows up here **)
...
```

I think this is confusing, because Grunt is reporting that the documentation is generated, which is false. And it doesn't show the output from JSdoc. 

When using normal JSdoc, the `--explain` tag doesn't generate any documenation, it just outputs it to `stdout` as JSON. I think it should output the `--explain` contents if it's given to Grunt also.

**Comment by krampstudio** [comment]
Sorry for the delay, I'll look at it.

**Comment by krampstudio** [comment]
Could you test again with the version 0.6.6

**Comment by krampstudio** [comment]
You've got the explain result in debug mode.
