### ISSUE TITLE
Request: Full names in index

### ISSUE THREAD

**Issue by Askelkana** [krampstudio/grunt-jsdoc#113]
The index's usefulness is greatly reduced by having the items listed by namespace but without any namespace information. This results in items being listed in apparently haphazard order, and difficult to find.

Items should be listed with full namespace name, i.e. X.Y.Z instead of just Z.

**Comment by krampstudio** [comment]
Please open an issue on https://github.com/jsdoc3/jsdoc the grunt plugin is only a wrapper for jsdoc.

**Comment by Askelkana** [comment]
Ah, my bad! I've written a few other issues as well. I'll move them. Muchos apologias!
