### ISSUE TITLE
0.6.x: JSDoc executable path resolved incorrect when not a direct dependency

### ISSUE THREAD

**Issue by lazd** [krampstudio/grunt-jsdoc#117]
[This little diddy here](https://github.com/krampstudio/grunt-jsdoc/blob/42a3e8fa757ed6eeca3c75c9a671344b05883eee/tasks/lib/exec.js#L97-L98) makes assumptions about the current working directory.

When `grunt-jsdoc` is not a direct dependency, the path to the JSDoc executable can't be resolved. For instance, we have a custom `coral-grunt-docsbuilder` dependency that uses `grunt-jsdoc` to build the docs. In 0.5.7, it was able to find the `jsdoc` executable just fine. When we did a `npm install --save-dev grunt-jsdoc@beta` and got 0.6.2, this stopped working.

I investigated and found that this check needs to be made relative to the task folder with the addition of something like:

```js
// Resolve the paths relative to the grunt-jsdoc task
paths[i] = path.resolve(__dirname+'/../../', paths[i]);
```

I'm not too happy with the above code. @krampstudio, maybe there's a simpler way to get the folder of the Grunt task or a better way to resolve these dependencies.

**Comment by krampstudio** [comment]
Yes, the assumption comes from grunt (see http://gruntjs.com/getting-started#the-gruntfile) where the gruntfile needs to be next to the package.json so node_modules folder is in the CWD.. 

This is not the first time someone points me this issue.

As a shortcut, you can set yourself the jsdoc exec path using the `jsdoc` option. Then I'll look on how to resolve this in a smarter way.

**Comment by lazd** [comment]
@krampstudio, hmm, looking at the code, it's definitely not Grunt's fault. Our `gruntfile.js` is in the same folder as the project's `package.json`, it's just that the Grunt plugins live inside of another module that defines Grunt tasks.

This can definitely be fixed within `grunt-jsdoc`, and my (ugly dirty hacky) code from above fixes it. I can submit a PR if you like.

**Comment by krampstudio** [comment]
I wasn't saying it's the grunt fault, it just leads me to make some assumptions. But anyway, it seems the jsdoc maintener will not expose jsdoc so I can't use `require.resolve('jsdoc')` to find the path. I'll try to implement it using  [resolve-bin](https://www.npmjs.com/package/resolve-bin)

**Comment by lazd** [comment]
@krampstudio sounds good!

**Comment by krampstudio** [comment]
I've publish the version `0.6.3 beta` that should fix your issue. Please let me know if it works for you.

**Comment by lazd** [comment]
@krampstudio I'll check into this on Monday, thanks!

**Comment by lazd** [comment]
@krampstudio `grunt-jsdoc@0.6.3` is working flawlessly with the following dependency tree:

```
└── component/
    ├── Gruntfile.js
    └── node_modules/
        └── component-docsbuilder/
            └── node_modules/
                └── grunt-jsdoc/
```

Thanks!

**Comment by krampstudio** [comment]
Cool!!!
