### ISSUE TITLE
Docstrap Menu header hides anchors

### ISSUE THREAD

**Issue by mwittig** [krampstudio/grunt-jsdoc#121]
Unfortunately, the docstrap menu header hides anchor lines, for example, if a link is clicked from the index. This way, a section heading (e.g. a function name) is hidden by the menu header most of the time which can be quite confusing. 

I found this posting which may be helpful to fixing this issue.
http://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

**Comment by krampstudio** [comment]
You should post this issue on the [docstrap](https://github.com/terryweiss/docstrap) repository

**Comment by mwittig** [comment]
Thanks for your feedback! I found this issue has already bee reported on docstrap:

https://github.com/terryweiss/docstrap/issues/51
      and related to this
             https://github.com/terryweiss/docstrap/issues/61

It may have been fixed with the latest release v0.4.15 which contains pull request #70 possibly fixing the issue. However, reported issues have not been updated on this since then. I'll give it a try and let you know about my findings.

**Comment by mwittig** [comment]
I always get confused by the fact that git release numbers do not necessarily match package releases! So, the latest package release (including v0.4.15 changes) is v0.5.2. This release depends on the latest jsdoc-3.3 release. 

I tweaked the dependencies as follows:
    "jsdoc": "~3.3.0-beta1",
    "ink-docstrap": "0.5.2"

Unfortunately, this causes problems when generating the docs.
     Warning: Arguments to path.resolve must be strings Used --force to continue.

**Comment by krampstudio** [comment]
which version of grunt-jsdoc do you use ? And could you log where does this issue appear ? (it will help me to decide to upgrade docstrap or not).

**Comment by mwittig** [comment]
I am using v0.5.8. Please advise further on how I should produce a log file.

C:\Users\marcus\Documents\Devel\ComX\cdk\client>grunt doc --debug --force
Started at Thu Feb 26 2015 18:58:01 GMT+0100 (Mitteleuropäische Zeit)

Running "jsdoc:dist" (jsdoc) task
[D] Task source: C:\Users\marcus\Documents\Devel\ComX\cdk\client\node_modules\grunt-jsdoc\tasks\jsdoc-plugin.js
[D] { destination: '../public/doc/cdk',
  template: 'node_modules/grunt-jsdoc/node_modules/ink-docstrap/template',
  configure: 'jsdocConfig.json' }
[D] nodePathC:\Users\marcus\Documents\Devel\ComX
[D] look up node_modules/jsdoc/jsdoc at node_modules/jsdoc/jsdoc
[D] look up node_modules/jsdoc/jsdoc at node_modules/grunt-jsdoc/
[D] look up node_modules/jsdoc/jsdoc at node_modules/grunt-jsdoc/node_modules/jsdoc/jsdoc
[D] look up node_modules/jsdoc/jsdoc at C:\Users\marcus\Documents\Devel\ComX/
[D] look up node_modules/jsdoc/jsdoc at C:\Users\marcus\Documents\Devel\ComX/node_modules/jsdoc/jsdoc
Warning: Arguments to path.resolve must be strings Used --force, continuing.

Done, but with warnings.

**Comment by krampstudio** [comment]
Try with the version 0.6.3 using `npm install grunt-jsdoc@beta`

**Comment by mwittig** [comment]
I have tried grunt-jsdoc@beta with docstrap v0.5.2 and now I get the error shown below. As far as I can see jsdoc 3.3 does not like my API markup, possibly due to parser error in the current beta1 release. Jsdoc generated some files though, and I can confirm that docstrap v0.5.2 fixes the described issue. 

As my API markup works fine with JSDoc 3.2, version 3.3 (beta1 and master) appears to be buggy or the documentation markup has been changed significantly. No matter what, I'll isolate the case and send a bug report to the jsdoc team. It's a pity, the docstrap release relies on unstable jsdoc release.

I'll keep you posted.

> An error occurs in jsdoc process:
>> 
>> fs.js:439
>>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
>>                  ^
>> Error: ENOENT, no such file or directory 'C:\Users\marcus\Documents\Devel\ComX\cdk\public\doc\cdk\ArchiveManager%20provides%20access%20to%20an%20ar...(truncated)

**Comment by krampstudio** [comment]
Agree with you. The jsdoc guys already told me the 3.3 isn't stable, this is why I keep a stable and a beta branch, docstrap should do the same.

**Comment by mwittig** [comment]
Wow, I have just leaned that the error was caused by erroneous markup in my source code documentation. For details see https://github.com/jsdoc3/jsdoc/issues/935

In my opinion the type of error message will leave developers in the dark who haven't learned JsDoc in the cradle :)

I will update my sources and will do another test run with grunt-jsdoc@beta tomorrow.

**Comment by mwittig** [comment]
Having updated my sources grunt-jsdoc@beta works fine for me with docstrap 0.5.2. However, the generated output has some anomalies. Page headings (e.g. Class Names) are printed twice, highlighted text on the index has same color than background, and the pages have an indentation offset of about 200 px. This is the case with the "spacelab" theme at least. I'll report this to the docstrap guys.

Conclusion: grunt-jsdoc@beta works with docstrap 0.5.2, but this docstrap release is a bit of a mixed bag. I think it is better to wait for the next docstrap release which hopefully will rely on a stable JSDoc release.

**Comment by mwittig** [comment]
fyi. I have reported the issue with docstrap v0.5.2. spacelab theme: https://github.com/terryweiss/docstrap/issues/85

**Comment by krampstudio** [comment]
Latest stable version of grunt-jsdoc (0.6.5) includes now docstrap 0.5.2

**Comment by mwittig** [comment]
Thanks for letting me know! Hopefully, a new docstrap release will be released soon to fix the reported issues with v0.5.2.

**Comment by krampstudio** [comment]
I've removed the direct dependency to docstrap in versino 1.0.0 then you could install the version you wish. 
Please reopen if needed.

Thanks

**Comment by mwittig** [comment]
Thanks! As far as I can seen the docstrap project is in a big mess, unfortunately.  I probably will roll my own fork to get a working version for my needs.

**Comment by mwittig** [comment]
fyi
Fortunatelly, ink-docstrap has a new maintainer who has been very busy over the weekend. Version 0.5.3 already looks promising as it fixes most of the issues I had.

**Comment by krampstudio** [comment]
Good news
