### ISSUE TITLE
Update grunt-jsdoc to the version preferred by lib creators?

### ISSUE THREAD

**Issue by cibulka** [krampstudio/grunt-jsdoc#122]
Hello!

I have some issue with JSDoc: https://github.com/jsdoc3/jsdoc/issues/941. Creators asked me to install 3.3.0 as "JSDoc 3.2.2 is the latest stable version, but it's very old at this point". So maybe you would want to update this plugin's package file as well?

Thanks for the plugin!

**Comment by krampstudio** [comment]
Hi, you can already get it by installing the beta version of the plugin. I follow the same stability flow than jsdoc3:
```
npm install --save-dev grunt-jsdoc@beta
```

ENjoy:

**Comment by cibulka** [comment]
Thanks!
