### ISSUE TITLE
Wrong path resolved in lib/exec.js

### ISSUE THREAD

**Issue by petarov** [krampstudio/grunt-jsdoc#125]
Hi,

For some reason I was constantly getting this error in `0.6.x`

    >> Unable to locate jsdoc
    Warning: Wrong installation/environnement Use --force to continue.

    Aborted due to warnings.

I **solved** this by modifying the base `paths` in `lib/exec.js`. However, this is a pure hack as I don't fully understand all that is happening here. 

```javascript
                //check first the base path into the cwd
                paths = [
            __dirname + '/../../../../node_modules/.bin/jsdoc',
            __dirname + '/../../../../node_modules/jsdoc/jsdoc.js'
```

EDIT: To  add, the path to the exec module on my system would be:

`/home/user/project/node_modules/grunt-jsdoc/tasks/lib/exec.js`

**Comment by krampstudio** [comment]
don't you have jsdoc available in `/home/user/project/node_modules/grunt-jsdoc/node_modules/jsdoc/` ?
As jsdoc is a dependency of grun-jsdoc you should get it that way.

**Comment by austinkeeley** [comment]
I had this issue and noticed it was because I had `jsdoc` explicitly provided in my `package.json` file, so it was getting installed first in `/node_modules/jsdoc`.  Moving it below the dependency for `grunt-jsdoc` or removing it all together should fix it.

**Comment by petarov** [comment]
@krampstudio No, in the case above `jsdoc` was placed directly in `/home/user/project/node_modules/jsdoc`. 

```
  "devDependencies": {
...
    "yuidocjs": "^0.3.50",
    "jsdoc": "~3.3.0-alpha10",
    "grunt-jsdoc": "~0.6.2-beta",
    "grunt-git": "^0.3.3",
    "typescript": "^1.4.1"
  }
```

Removing the jsdoc dependency from `package.json` as @austinkeeley suggested seems to have resolved the issue. Thanks!

**Comment by uloco** [comment]
`angular-jsdoc` needs a `jsdoc` installation on it's own, so how can I use both, `grunt-jsdoc` and `jsdoc` simultaneously?
