### ISSUE TITLE
Prevent source code in documentation

### ISSUE THREAD

**Issue by admiller97** [krampstudio/grunt-jsdoc#127]
Is there a way to prevent source code from being placed into the output documentation?  http://stackoverflow.com/questions/20907501/how-can-i-omit-the-source-links-in-jsdoc mentions a solution, but not sure how I'd implement that in the grunt file?

**Comment by krampstudio** [comment]
Hi,

You should use a `jsdoc.conf` file where you can add this option.

**Comment by admiller97** [comment]
This worked, thanks!
conf.json:
{
  "source": {
    "include": "app/js/sourcefile.js"
  },
  "templates": {
    "default": {
      "outputSourceFiles": false
    }
  }
}
