### ISSUE TITLE
Index page and other pages show multiple heading 

### ISSUE THREAD

**Issue by djonnala** [krampstudio/grunt-jsdoc#131]
index page and other pages like modules show multiple headings in the html file. I am not able to figure out how to resolve this.

![untitled](https://cloud.githubusercontent.com/assets/12037869/7716225/7d03af4c-fe44-11e4-93fe-77d921722951.png)

**Comment by krampstudio** [comment]
This plugin is a wrapper to https://github.com/jsdoc3/jsdoc. Please report them the issue.
