### ISSUE TITLE
package.json support

### ISSUE THREAD

**Issue by latel** [krampstudio/grunt-jsdoc#132]
is there any plan for  package.json integration support?
as described on jsdoc3: [http://usejsdoc.org/about-including-package.html](http://usejsdoc.org/about-including-package.html)

**Comment by krampstudio** [comment]
I'll add the option, but it should work (using the beta version, that will become stable soon) just by adding the `package.json` file to your source list.

**Comment by krampstudio** [comment]
The `package` option is supported.

**Comment by krampstudio** [comment]
I've added a test case and this option works.
