### ISSUE TITLE
Absolute paths used on Windows

### ISSUE THREAD

**Issue by Download** [krampstudio/grunt-jsdoc#135]
I think I'm seeing this bug in my jsdoc output from Grunt:

https://github.com/terryweiss/docstrap/issues/44

I'm using DocStrap. I think you include DocStrap with the grunt plugin right? Can it be you are still on an older version that has this bug?

Sorry if it's user error, i'm pretty new to Grunt, JsDoc and this plugin  :)

**Comment by krampstudio** [comment]
I'm linking to docstrap version 0.5.2, could you reinstall the plugin ?

**Comment by Download** [comment]
I will try... Could you give me a tip how to do it?
Some npm commands I presume?

**Comment by krampstudio** [comment]
just remove the `node_modules` folder and run again `npm install`

**Comment by Download** [comment]
Did as you asked and I see (among lots of other output):

    grunt-jsdoc@0.6.7 node_modules\grunt-jsdoc
    ├── jsdoc@3.3.0 (escape-string-regexp@1.0.3, strip-json-comments@1.0.2, taffydb@2.6.2, underscore@1.7.0, js2xmlparser@0.1.9, async@0.9.2, requizzle@0.2.1, wrench@1.5.8, marked@0.3.3, esprima@1.1.0-dev-harmony, catharsis@0.8.6)
    └── ink-docstrap@0.5.2 (moment@2.6.0)

I will try out if it worked and let you know

**Comment by Download** [comment]
Running "jsdoc:dist" (jsdoc) task
    Documentation generated to C:\Users\Stijn\Documents\GitHub\suid\doc

I still see the issue. It generates a file called `C__Users_Stijn_Documents_GitHub_suid_src_suid.js.html` and 'absolute' path links to it.

My grunt file contains this:

	jsdoc : {
		dist : {
			src: ['src/*.js', 'test/*.js'],
			options: {
				destination: 'doc',
				template : "node_modules/grunt-jsdoc/node_modules/ink-docstrap/template",
				configure: "node_modules/grunt-jsdoc/node_modules/ink-docstrap/template/jsdoc.conf.json"
			}
		}
	},

I will try with `./src/*.js` instead of `src/*.js` and see if that makes a difference.

**Comment by Download** [comment]
Nope it made no difference.

Am I doing something wrong? I notice that jsdoc logs an absolute path in it's output:

    Documentation generated to C:\Users\Stijn\Documents\GitHub\suid\doc

Is it supposed to? I'm new to JSDoc and Grunt both so I really don't know what to expect.
I also saw that the bug on JSDoc was reopened at some point because the bug came back. Maybe it came back again?

**Comment by krampstudio** [comment]
As docstrap isn't in the plugin anymore, I'm closing the issue.

**Comment by Download** [comment]
I gave up on JSDoc as keep editing the file to fix the absolute path was a pain.
