### ISSUE TITLE
"Cannot read property 'split' of undefined" error

### ISSUE THREAD

**Issue by piranna** [krampstudio/grunt-jsdoc#136]
With grunt-jsdoc 0.6.6 I'm getting the next error:

```Javascript
Running "jsdoc:all" (jsdoc) task
Verifying property jsdoc.all exists in config...OK
Files: package.json, README.md, lib/WebRtcPeer.js, lib/browser.js, lib/index.js, test/WebRtcPeer.js, test/_common.js -> doc/jsdoc
Options: private, ignoreWarnings=false, timeout=60
Warning: Cannot read property 'split' of undefined Use --force to continue.
```

At the same time, executing jsdoc 3.3.0 (the one installed as dependency of grunt-jsdoc) directly it works correctly:

```bash
[piranna@Mabuk:~/workspace/kurento-utils-js]
 (master) > node_modules/grunt-jsdoc/node_modules/.bin/jsdoc package.json README.md lib/*.js test/*.js -d doc/jsdoc --verbose
Parsing /home/piranna/workspace/kurento-utils-js/lib/browser.js ...complete.
Parsing /home/piranna/workspace/kurento-utils-js/lib/index.js ...complete.
Parsing /home/piranna/workspace/kurento-utils-js/lib/WebRtcPeer.js ...complete.
Parsing /home/piranna/workspace/kurento-utils-js/test/WebRtcPeer.js ...complete.
Generating output files...complete.
Finished running in 0.63 seconds.
```

**Comment by piranna** [comment]
The configuration of Gruntfile is

```Javascript
    jsdoc: {
      all: {
        src: ['package.json', 'README.md', 'lib/**/*.js', 'test/*.js'],
        dest: 'doc/jsdoc'
      }
    },
```

**Comment by krampstudio** [comment]
What's your OS? 
Also could you do the following tests for me : 
- in `node_modules/grunt-jsdoc/tasks/lib/exec.js` could you add `console.log('nodePath',  nodePath);` line 66, run it again and give me the result.
- run `grunt jsdoc:all --debug` copy/paste the command after the `Running :` tag and try it.

thanks

**Comment by piranna** [comment]
> What's your OS?

Ubuntu 15.04


> in node_modules/grunt-jsdoc/tasks/lib/exec.js could you add console.log('nodePath', nodePath); line 66, run it again and give me the result.

```Javascript
nodePath /usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
```

Just before the paths array.


> run grunt jsdoc:all --debug copy/paste the command after the Running : tag and try it.

```Javascript
Running "jsdoc:all" (jsdoc) task
[D] Task source: /home/piranna/workspace/kurento-utils-js/node_modules/grunt-jsdoc/tasks/jsdoc-plugin.js
nodePath /usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
[D] Using jsdoc from : node_modules/grunt-jsdoc/node_modules/.bin/jsdoc
[D] Running : node_modules/grunt-jsdoc/node_modules/.bin/jsdoc --destination doc/jsdoc --private package.json README.md lib/WebRtcPeer.js lib/browser.js lib/index.js test/WebRtcPeer.js test/_common.js
Fatal error: Arguments to path.resolve must be strings
```

> thanks

You are welcome :-)

**Comment by piranna** [comment]
Some of my colleages that don't have the package.json entry on the jsdoc are having the same problem, too.

**Comment by krampstudio** [comment]
Could you also give me the value of `paths` in the same file, and do you have jsdoc installed globally ? 
Then I'll fix the lookup method (as soon as I'm able to reproduce the issue).

**Comment by piranna** [comment]
> Could you also give me the value of paths in the same file,

```Javascript
		//check first the base path into the cwd
		paths = [
            __dirname + '/../../node_modules/.bin/jsdoc',
            __dirname + '/../../node_modules/jsdoc/jsdoc.js'
        ];
```

I didn't touched it, anyway...


> and do you have jsdoc installed globally ?

No, I don't, I've used the one that grunt-jsdoc installed.

> Then I'll fix the lookup method (as soon as I'm able to reproduce the issue).

Ok, thank you. You could be able to reproduce by [downloading the project code](https://github.com/Kurento/kurento-utils-js) and upgrading the grunt-jsdoc dependency by hand.

**Comment by krampstudio** [comment]
:) I meant the value of the variable at runtime... but anyway with your project I'll try to reproduce the issue. 
BTW your project seems interesting !

**Comment by krampstudio** [comment]
For now you can make it work by updating your config: 
```javascript
    jsdoc: {
      all: {
        src: ['README.md', 'lib/**/*.js', 'test/*.js'],
        options : {
            destination: 'doc/jsdoc'
        }
      }
    },
```

**Comment by krampstudio** [comment]
0.6.7 should fix it anyway

**Comment by piranna** [comment]
Yes, 0.6.7 has fixed it, thank you for doing it so quick! :-)

**Comment by krampstudio** [comment]
Cool!

**Comment by piranna** [comment]
:+1:
