### ISSUE TITLE
Task fails if no source files present

### ISSUE THREAD

**Issue by davetgreen** [krampstudio/grunt-jsdoc#137]
Is there any way to prevent this behaviour? I'm using grunt-jsdoc as part of a front-end boilerplate and it's entirely possible - such as in this test case - that there user won't have any JS in the 'src' folder when the first re-build happens. 

I've got `ignoreWarnings` set to true but I'm guessing this is to silence a different kind of warning?

Any help greatly appreciated! :)

Thanks,
Dave

**Comment by davetgreen** [comment]
![jsdoc-error](https://cloud.githubusercontent.com/assets/3214928/7966725/d01d7ca0-0a1d-11e5-91b8-9715efecaa0d.png)

**Comment by krampstudio** [comment]
This should be fixed in version 2.0.0, please reopen if not.

**Comment by davetgreen** [comment]
@krampstudio Thank you!
