### ISSUE TITLE
ENAMETOOLONG on latest install

### ISSUE THREAD

**Issue by perry-mitchell** [krampstudio/grunt-jsdoc#142]
When installing the latest build, I receive the following error:

```
$ npm install grunt-jsdoc@latest
npm WARN peerDependencies The peer dependency grunt@^0.4.0 included from grunt-jsdoc will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! tar.unpack untar error /home/perry/.npm/ink-docstrap/0.5.2/package.tgz
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "grunt-jsdoc@latest"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3
npm ERR! path /home/perry/Temp/node_modules/grunt-jsdoc/node_modules/ink-docstrap/themes/paper/module-documents_probe.This%2520is%2520not%2520actually%2520a%2520class,%2520but%2520an%2520artifact%2520of%2520the%2520documentation%2520system.html
npm ERR! code ENAMETOOLONG
npm ERR! errno -36

npm ERR! ENAMETOOLONG, open '/home/perry/Temp/node_modules/grunt-jsdoc/node_modules/ink-docstrap/themes/paper/module-documents_probe.This%2520is%2520not%2520actually%2520a%2520class,%2520but%2520an%2520artifact%2520of%2520the%2520documentation%2520system.html'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/perry/Temp/npm-debug.log
```

Node and NPM versions are included in that output. Running on Ubuntu 14.04.

I've dropped the entire npm-debug.log on pastebin [here](http://pastebin.com/Ey7x5czn).

**Comment by bobholt** [comment]
This is due to the ink-docstrap dependency running docs against this line, which generates the filename causing the ENAMETOOLONG error:

https://github.com/terryweiss/docstrap/blob/master/fixtures/documents/probe.js#L1004

See also:
- https://github.com/terryweiss/docstrap/issues/103
- https://github.com/terryweiss/docstrap/issues/109

That lib is actively looking for new maintainers:
https://github.com/terryweiss/docstrap/issues/75

**Comment by krampstudio** [comment]
I might remove the direct dep to that lib and let people to choose to install it. But in the meanwhile, I'll fix the dep to a working version

**Comment by bobholt** [comment]
:+1:

**Comment by atanaschristov** [comment]
I experience the same issue.

**Comment by joh-klein** [comment]
I have this issue too. Is everybody else using paths shorter then 41 characters? Or how do you get around this bug?

**Comment by krampstudio** [comment]
I've removed the dependency to docstrap in version 1.0.0
Using this version the problem shouldn't affect the plugin install anymore.
Please reopen if needed.

Thanks!
