### ISSUE TITLE
"Wrong installation/environnement" if both grunt-jsdoc and jsdoc are dependencies

### ISSUE THREAD

**Issue by BlueRaja** [krampstudio/grunt-jsdoc#143]
As title says.  `grunt-jsdoc` can't find jsdoc if it's installed as a dependency of my project.  If I remove the `jsdoc` dependency and rerun `npm install`, it works just fine.

**Comment by krampstudio** [comment]
Could you paste your `package.json` config, so I can try to reproduce. Is there any error or do you expect grunt-jsdoc to link the jsdoc at the same level ?

**Comment by krampstudio** [comment]
https://github.com/krampstudio/grunt-jsdoc/pull/139 should fix it. I yes, I'll merge it soon (hopefully).

**Comment by krampstudio** [comment]
Fixed by 0.6.8. Please reopen if not.
