### ISSUE TITLE
crash on windows

### ISSUE THREAD

**Issue by gbaumgart** [krampstudio/grunt-jsdoc#144]
did you test on windows? its not running the jsdoc binary from bin, but the jsdoc.js file instead. That causes a fatal crash and opens an error dialog. 

thanks

**Comment by mc007** [comment]
sure, here you go: 
![image](https://cloud.githubusercontent.com/assets/1205100/9686481/7f417a52-5324-11e5-9314-cc339c12fa80.png)

doesn't happen on linux. another user reported this on the same lib as well.

**Comment by krampstudio** [comment]
The PR https://github.com/krampstudio/grunt-jsdoc/pull/146 should fix it. I guess it's because js files are configured to be opened  by MS JScript compiler instead of node.

**Comment by krampstudio** [comment]
Should be fixed in 0.6.9. If not please reopen.
