### ISSUE TITLE
support for npm@3 flattened modules

### ISSUE THREAD

**Issue by leobalter** [krampstudio/grunt-jsdoc#148]
npm introduced flattened modules on 3.x.x versions, since then, grunt-jsdoc needs to be adapted to handle this or it breaks.

```
Running "jsdoc:src" (jsdoc) task
>> FATAL: Unable to load template: Cannot find module 'node_modules/grunt-jsdoc/node_modules/ink-docstrap/template/publish'
Warning: jsdoc terminated with a non-zero exit code Use --force to continue.
```

**Comment by leobalter** [comment]
maybe it's my bad.

On my task options I was setting `template: 'node_modules/grunt-jsdoc/node_modules/ink-docstrap/template',` 

This still requires an update on the readme file.

**Comment by krampstudio** [comment]
Good point. I though npm 3 was still in beta and had some time left, but it seems it's time to support it.

**Comment by leobalter** [comment]
`npm i -g npm` already brings it.
