### ISSUE TITLE
Fatal error: spawn cmd ENOENT

### ISSUE THREAD

**Issue by silentsnooc** [krampstudio/grunt-jsdoc#152]
I don't know what the problem is but as I run Grunt I'm getting this output here:

![capture](https://cloud.githubusercontent.com/assets/1429426/10590776/d60c55bc-76b2-11e5-9c1e-7424a56feb87.PNG)

I have tried deleting `bower_components` and `node_modules` and rerun `bower install & npm install` but that didn't resolve the issue like stated elsewhere.

What's the problem here. I don't see it ..

**Comment by krampstudio** [comment]
What's your version of the plugin.
When you run `cmd /c node_modules...` does it work ?

**Comment by silentsnooc** [comment]
@krampstudio The version I declare in package.json is `"grunt-jsdoc": "^1.0.0"`.

Sorry, what is `cmd /c node_modules..`?

**Comment by krampstudio** [comment]
yes, the plugin will just run the given command. So if you try to put that command in a terminal, then you can see what the error is. 
Could you also paste your grunt configuration for this task ?

**Comment by silentsnooc** [comment]
Okay I have now issued 

    node_modules\grunt-jsdoc\node_modules\.bin\jsdoc --configure jsdoc.conf.json --destination tmp/ --private --template node_modules\ink-docstrap/template js/controller.test.js js/view.test.js README.md package.json

In my build directory. I am not getting an error message or something. The documentation now appears to get build in `tmp\javascript_toy_cpu\1.0.0\`. It seems that jsdoc is working as it should. O_o

In this case this issue relates to grunt but any idea what could cause the problem with grunt?

------

Btw. here is my `package.json´ file:

```json
{
  "name": "javascript_toy_cpu",
  "version": "1.0.0",
  "description": "An implementation of the Princeton Toy CPU.",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {},
  "keywords": [
    "widget"
  ],
  "author": "Stefan Falk <s.falk@student.tugraz.at>",
  "license": "Apache-2.0",
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.1",
    "grunt-contrib-copy": "^0.8.2",
    "grunt-contrib-cssmin": "^0.14.0",
    "grunt-contrib-htmlmin": "^0.5.0",
    "grunt-contrib-jshint": "^0.11.3",
    "grunt-contrib-uglify": "^0.9.2",
    "grunt-jsdoc": "^1.0.0",
    "grunt-processhtml": "^0.3.8",
    "grunt-remove-calls": "0.0.6",
    "grunt-xmlpoke": "^0.8.0",
    "ink-docstrap": "^0.5.2",
    "requirejs": "^2.1.20"
  }
}
```

**Comment by krampstudio** [comment]
I've moved to a cross platform spawn lib from version 2.0.0, could you test with this version

**Comment by krampstudio** [comment]
any update ?

**Comment by krampstudio** [comment]
Closing. Please reopen one still encounter the problem.
