### ISSUE TITLE
Way to parse just the comments?

### ISSUE THREAD

**Issue by robgrimball** [krampstudio/grunt-jsdoc#153]
I am trying to run grunt-jsdoc through my code, unfortunately a significant amount of my code uses ES6 generators.  I realize that jsdoc does not support ES6, but was wondering if there was a way to basically have it ignore the source code for the most part, just looking at the comment blocks for what information it needs so it will still document those files, just not try to be so smart about it so to speak.

Thanks!

**Comment by krampstudio** [comment]
This plugin is _just_ a wrapper around jsdoc, so everything takes place at the jsdoc level. 
The generator parsing error is documented by https://github.com/jsdoc3/jsdoc/issues/555 and the resolution will come in jsdoc 3.4.0.
One of the solution would be for you to use the development version of jsdoc.

**Comment by robgrimball** [comment]
Thanks @krampstudio, I have gone ahead and just changed the gruntjs-doc package.json to point to the master branch of the jsdoc3 repo for now until they get that tagged and then subsequently when that tag is in use here.  I'm sure by the time we are ready to publish this will resolve itself out and I won't have to have that manual hack in the package.json.
