### ISSUE TITLE
Doesn't work inside a symlinked directory (Windows) - shell not recognized

### ISSUE THREAD

**Issue by JD-Robbs** [krampstudio/grunt-jsdoc#156]
If you symlink a directory in Windows from, say "C:\Users\User\Dropbox" to "C:\dev\www", it reports that `...\...\...\...\Users\User\Dropbox\[...]` is `not recognized as an internal or external command`.

Just wondering if that's _fixable_?
##

**Comment by krampstudio** [comment]
Where is used the symlink ?
Could you please paste the command outputted with the `--debug` flag

**Comment by krampstudio** [comment]
any update ?

**Comment by krampstudio** [comment]
Could you test it with the new version 2.0.0 since we use now a cross platform spawn lib.

**Comment by JD-Robbs** [comment]
My sincere apologies - I didn't see any notifications re. this thread for some reason. It's been solved for a while now. 👍
