### ISSUE TITLE
Different `private` behavior

### ISSUE THREAD

**Issue by adrianlee44** [krampstudio/grunt-jsdoc#157]
For jsdoc, the default behavior for private functions is to not render them. Using jsdoc command line, private default to `undefined`.

However, looking at `grunt-jsdoc`, `private` is default to true (https://github.com/krampstudio/grunt-jsdoc/blob/master/tasks/jsdoc-plugin.js#L37). Is this by design? If so, some documentation on this would be nice.

Thank for the grunt plugin.

**Comment by Flowkap** [comment]
I found out it's only true if configuring a jsdoc.json config file.. Even more strange: Then it defaults to treat underscored modules/classes private as well but not when using the pricate:false setting in options.

**Comment by krampstudio** [comment]
Yes, this is by design. It was to fit my needs when I wrote the plugin first. But now as the plugin is widely used, I might consider sticking the jsdoc behavior.

**Comment by adrianlee44** [comment]
Thanks for your response, @krampstudio! Any chance of removing that line and stick with jsdoc default behavior?

**Comment by krampstudio** [comment]
This is now part of version 2.0.0
