### ISSUE TITLE
Cannot ignore files using Globbing patterns

### ISSUE THREAD

**Issue by robinsving** [krampstudio/grunt-jsdoc#158]
Trying to use the grunt-jsdoc plugin to generate all me relevant jsdoc using this command:
```
        jsdoc: {
            src: ["app/**/*.js", "!app/shared/atmosphere.js"],
            dist: 'doc/'
        }
```
But the atmosphere.js is still picked up by the plugin. Am I doing something incorrectly, or is Globbing patterns not supported?

**Comment by krampstudio** [comment]
It should be working. 
Could you please paste the output of the command with the `--debug flag`

**Comment by robinsving** [comment]
Had forgotten to add the name of the jsdoc setting. It may have been the reason. This works
        ```
jsdoc: {
            name: {
                src: ["app/**/*.js", "!app/shared/atmosphere.js"],
                options: {
                    destination: 'dist/doc'
                }
            }
        }
```
