### ISSUE TITLE
unmet peer dependency

### ISSUE THREAD

**Issue by julmot** [krampstudio/grunt-jsdoc#159]
Running

```javascript
npm install grunt-jsdoc --save-dev
```

causes:

![err](https://cloud.githubusercontent.com/assets/8310677/13250604/3ded2ed2-da2b-11e5-92ef-fb7d04702348.png)

**Comment by krampstudio** [comment]
npm warns you because you need grunt in your project. See https://docs.npmjs.com/files/package.json#peerdependencies
