### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by julmot** [krampstudio/grunt-jsdoc#160]
Gruntfile.js
```javascript
		jsdoc: {
			dist: {
				src: ['src/myfile.js'],
				options: {
					destination: 'doc'
				}
			}
		}
```

myfile.js:
```javascript
/**
 * supply - description
 *
 * @param  {number} a description
 * @param  {number} b description
 * @return {number}   description
 */
function supply(a, b){
	return a * b;
}
```

Running `grunt jsdoc` will result:

![jsdoc_warning](https://cloud.githubusercontent.com/assets/8310677/13252285/2e8ab6fc-da36-11e5-83d1-317863590c6e.png)

**Comment by krampstudio** [comment]
Hi, the error seems to be outside the jsdoc plugin definition, could you paste the whole Gruntfile.js please ?

**Comment by krampstudio** [comment]
It seems unrelated to the plugin itself, please reopen if you're not agree.
