### ISSUE TITLE
deprecated cross-spawn-async@2.2.4

### ISSUE THREAD

**Issue by superclarkk** [krampstudio/grunt-jsdoc#165]
~~~
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
~~~

Running `npm ls cross-spawn-async@2.2.4` indicates that grunt-jsdoc has it as a dependency.

**Comment by krampstudio** [comment]
solved by https://github.com/krampstudio/grunt-jsdoc/pull/167
