### ISSUE TITLE
Task Events

### ISSUE THREAD

**Issue by msartor92** [krampstudio/grunt-jsdoc#166]
I'm using your package into my project but i need tu run multiple instances. 

- Could you add to the option  or somewhere a paramter to set a callback funtion which you call when the task is completed?

-  Another solution could be you save an internal copy of the config.
- Or at least return an event after the documentation generated log print

I need these because if I run multiple task which have different initConfig data the last one runned overwrite all the previous.
If you want I could help in developing

**Comment by krampstudio** [comment]
I don't really get the problem (the task is synchronous), but if you'd like to plug on the plugin's lifecycle the best would be to listen for events.

**Comment by msartor92** [comment]
The task is synchronous but the initialConfig parameters is shared. So if I need to run multiple task on different source and dest path and I use a template to edit the initialConfig the new one overwrite the old one

**Comment by krampstudio** [comment]
Alright, I'll add some events

**Comment by krampstudio** [comment]
Could you check https://github.com/krampstudio/grunt-jsdoc/pull/168 , then you'll listen for the end of the task using : 
```js
grunt.event.on('generated.jsdoc', function(){
    //you're done
});
```

**Comment by msartor92** [comment]
Very nice solution, it work fine! thank you to have solved so fast!!
