### ISSUE TITLE
No source files defined

### ISSUE THREAD

**Issue by befreestudios** [krampstudio/grunt-jsdoc#169]
Hi There... running into an issue, its saying that No source files have been defined when they clearly have... Has anyone seen this already, or know a solution? Thanks in advance.

error:
```Running "jsdoc:jsdoc" (jsdoc) task
>> No source files defined
Warning: Wrong configuration Use --force to continue.

Aborted due to warnings.```

my task
```{
  "jsdoc" : {
    "dist" : {
      "src": ["public/js/**/*.js"],
      "options": {
        "destination": "docs"
      }
    }
  }
}```

**Comment by krampstudio** [comment]
Hi, 
If you run  `grunt jsdoc:jsdoc`  you need to have the `jsdoc` subtask defined.
With your configuration you should run `grunt jsdoc:dist`

**Comment by befreestudios** [comment]
@krampstudio Hey, Nice Catch!!! I moved all my grunt tasks to external files so I didn't even notice the nested nature and task name being incorrect. Sometimes all it takes is a second set of eyes... thanks, your suggestion fixed it...

My Config, that works now...

```
{
  "jsdoc" : {
    "src": ["public/js/**/*.js"],
    "options": {
      "destination": "docs",
      "template": "node_modules/ink-docstrap/template"
    }
  }
}
```
