### ISSUE TITLE
JSDoc is now in version 3.4.1 which resolves the hideous Github download dependency

### ISSUE THREAD

**Issue by atc-** [krampstudio/grunt-jsdoc#174]
Please can you bounce the version of jsdoc you rely on? Jsdoc recently resolved a long-standing (and phenomenally frustrating) [feature](https://github.com/jsdoc3/jsdoc/issues/961) of downloading taffydb via Git.

Bumping your version to 3.4.1 (and publishing to NPMJS ;)) would mean those of us using your plugin won't suffer from this issue any longer.

**Comment by krampstudio** [comment]
It's a bugfix version, so all furthers `npm install` will always use the version `3.4.1` of jsdoc.

**Comment by atc-** [comment]
Could've sworn my fresh `npm install` didn't resolve that despite your semantic versioning expression. I'll test in a fresh project...Hold up! :)

**Comment by krampstudio** [comment]
or `npm update` to fix outdated versions.

**Comment by atc-** [comment]
Just did a fresh project and it pulled in 3.4.1. I wonder if the internal Nexus had it cached or something. Anyhow, nothing to see here! :)

:whale:
