### ISSUE TITLE
Include symbols marked with @private with the "-p" cli argument

### ISSUE THREAD

**Issue by natterstefan** [krampstudio/grunt-jsdoc#176]
Hi, as my title says I want to mark some functions in my `@class` as private but want them to be visible in the JsDocs template/site.

In the JSDocs docu I saw it should be achievable with `-p, --private` ([read more here](http://usejsdoc.org/about-commandline.html)).

How can I enable this with your plugin?

**Comment by krampstudio** [comment]
Hi all jsdoc options are supported through the `options`. In your Gruntfile.js, you'll have something like : 

```js
grunt.initConfig({
  jsdoc : {
     dist : {
         src: ['**/*.js'],
         dest : 'doc',
         options: {
           private : true
         }
     }
  }
});
```

**Comment by krampstudio** [comment]
@natterstefan did the configuration above help you ?

**Comment by natterstefan** [comment]
Hi @krampstudio, thanks for your response. Too be honest I am not sure and can't recall. Sorry. So, it's fine for me if you close the issue. If it's still an issue, somebody else can reopen it again.
