### ISSUE TITLE
JSDoc dependency breaking build

### ISSUE THREAD

**Issue by TwR-Slice** [krampstudio/grunt-jsdoc#177]
the dependency of jsdoc should change from "^3.4.0" to "~3.4.0" in version [1.1.0](https://github.com/krampstudio/grunt-jsdoc/tree/1.1.0)

JSDoc introduced babylon in 3.5.0 which is producing errors when building on older node versions.

**Comment by Mydayyy** [comment]
Hi,

we do encounter the same problem. I just looked a bit more into the issue:

The dependency of JSDoc is written as ^3.4.0 which also includes 3.5.0. ( Can be calculated [here](https://semver.npmjs.com) in case one is unfamiliar with semver ). 

As jsdoc released the first 3.5.0 package on 2017-07-10T02:26:25.790Z, we run into issues during doc creation now, as npm is installing jsdoc 3.5.x. 

It would be nice if it were possible to use ~3.4.0 as its dependency.

Best Regards
~Mydayyy

**Comment by krampstudio** [comment]
Yep I'll try to fix this asap

**Comment by krampstudio** [comment]
Please let me know if [version 2.1.1](https://www.npmjs.com/package/grunt-jsdoc) fix it for you all.

**Comment by Mydayyy** [comment]
Hi,

the problem is fixed on our side! Thanks you so much for your quick reaction!

Best Regards
~Mydayyy

**Comment by TwR-Slice** [comment]
I can confirm that the issue is resolved!

Thank you for your quick fix!
