### ISSUE TITLE
jsdoc not built

### ISSUE THREAD

**Issue by MidnightJava** [krampstudio/grunt-jsdoc#182]
When I run `grunt-jsdoc`, `jsdoc` fails because none of its dependencies are present. In fact, there is no `node_modules` directory in `...grunt-jsdoc/node_modules/jsdoc`. I cd into that directory and run `npm i`, and then I can execute `grunt-jsdoc` without errors.

I assume I should not have to do that. Is there something else I need to do to cause `jsdoc` dependencies to be built?

**Comment by krampstudio** [comment]
Hello, what's your `npm` version and could your please post the `package.json` that includes `grunt-jsdoc` ?

**Comment by MidnightJava** [comment]
Yes, I do have the required packages installed there (e.g. underscore is the first one that fails dependency check). But if I delete the node_modules folder inside the `grunt-jsdoc/node_modules/jsdoc` folder, `jsdoc` throws an exception, like this:

```
$ grunt jsdoc
Running "jsdoc:project1" (jsdoc) task
>> An error occurs in jsdoc process:
>> js: "/opt/git/project1/node_modules/grunt-jsdoc/node_modules/jsdoc/jsdoc.js", line 316: exception from uncaught JavaScript throw: Error: Module "underscore" not found.
Warning: jsdoc failure Use --force to continue.

Aborted due to warnings.
```
```
 $ ls ./node_modules/ | grep underscore
underscore
underscore.string

```

**Comment by MidnightJava** [comment]
Here is the `jsdoc` task entry in Gruntfile.js

```
jsdoc: {
            project1: {
                src: ['js/*.js'],
                options: {
                    destination: 'doc',
                    template: 'docstrap-master/template',
                    configure: 'docstrap-master/conf.json'
                }
            }
        },
```

**Comment by krampstudio** [comment]
`"grunt-jsdoc": "^0.5.4",`
is a pretty old version that works only with old versions of `npm` and old version of `jsdoc`. 

You have multiple possibilities : 
1. Use a previous version of npm
2. Update `grunt-jsdoc` to a version still compatible with your other grunt peer dependencies but that supports newer `npm`. Check the [release history](https://github.com/krampstudio/grunt-jsdoc#release-history) and [compatibility](https://github.com/krampstudio/grunt-jsdoc#compatibility) sections.
3. Upgrade all the grunts packages

**Comment by MidnightJava** [comment]
Thanks for your help! I updated to the latest version of `grunt-jsdoc`, and it works properly. Don't know why I didn't think of trying that first.
