### ISSUE TITLE
Help!!! Why I get syntaxError when run "grunt jsdoc" 

### ISSUE THREAD

**Issue by adele-ghsoft** [krampstudio/grunt-jsdoc#183]
i tried to generate with angualrjs 1.6.10 
but I had a systaxError! I didn know why. 
My source code never has !== .
this is shown when i use "template: 'node_modules/angular-jsdoc/angular-template'," in Gruntfile.js.

I had the following configuration.

npm install..
    "angular-jsdoc": "1.4.1",
    "grunt-jsdoc": "2.2.1"

config in Gruntfile.js ...
   require('grunt-jsdoc')(grunt);
   ...
    jsdoc: {
      dist: {
        src: ["<%=app.web%>/js"],
        options: {
          destination: 'build/docs',
          configure: 'node_modules/angular-jsdoc/common/conf.json',
          template: 'node_modules/angular-jsdoc/angular-template',
          verbose: true,
          recurse: true
        }
      }
    }

>> /project/workspace/web/node_modules/angular-template/index.js:98
>>         throw e;
>>         ^
>>
>> SyntaxError: Unexpected token !==
>>     at new Function (<anonymous>)
>>     at templateFunc (/project/workspace/web/node_modules/js-template/index.js:56:12)
>>     at jsTemplate (/project/workspace/web/node_modules/js-template/index.js:65:18)
>>     at angularTemplate (/project/workspace/web/node_modules/angular-template/index.js:84:14)
>>     at generateSourceFiles (/project/workspace/web/node_modules/angular-jsdoc/angular-template/publish.js:100:16)
>>     at Object.exports.publish (/project/workspace/web/node_modules/angular-jsdoc/angular-template/publish.js:283:3)
>>     at Object.module.exports.cli.generateDocs (/project/workspace/web/node_modules/grunt-jsdoc/node_modules/jsdoc/cli.js:448:35)
>>     at Object.module.exports.cli.processParseResults (/project/workspace/web/node_modules/grunt-jsdoc/node_modules/jsdoc/cli.js:399:20)
>>     at module.exports.cli.main (/project/workspace/web/node_modules/grunt-jsdoc/node_modules/jsdoc/cli.js:240:14)
>>     at Object.module.exports.cli.runCommand (/project/workspace/web/node_modules/grunt-jsdoc/node_modules/jsdoc/cli.js:189:5)
>>     at /project/workspace/web/node_modules/grunt-jsdoc/node_modules/jsdoc/jsdoc.js:105:9
>>     at Object.<anonymous> (/project/workspace/web/node_modules/grunt-jsdoc/node_modules/jsdoc/jsdoc.js:106:3)
>>     at Module._compile (module.js:643:30)
>>     at Object.Module._extensions..js (module.js:654:10)
>>     at Module.load (module.js:556:32)
>>     at tryModuleLoad (module.js:499:12)
Warning: jsdoc terminated with a non-zero exit code Use --force to continue.

**Comment by krampstudio** [comment]
It looks like the generated function from `js-template` execute an invalid function. Check what's in `strFunc` see https://github.com/allenhwkim/js-template/blob/v0.1.3/index.js#L55 and you'll get your answer.
`grunt-jsdoc` is a wrapper to `jsdoc`, if you execute the `jsdoc` command manually, you'll get the same issue. Please report the bug to the appropriate repository if any.
