### ISSUE TITLE
Fails on Windows

### ISSUE THREAD

**Issue by muxa** [krampstudio/grunt-jsdoc#37]
I'm using relative paths

```
        jsdoc : {
            dist : {
                src: ['appv2/**/*.js'], 
                options: {
                    destination: 'doc'
                }
            }
        }
```

And getting the following error:

```
E:\Users\md\Documents\Visual Studio 2010\Projects\MyProject>grunt jsdoc
Running "jsdoc:dist" (jsdoc) task
>> An error occurs in jsdoc process:
>> 'E:\Users\md\Documents\Visual' is not recognized as an internal or external c
ommand,
>> operable program or batch file.
Warning: jsdoc failure Use --force to continue.

Aborted due to warnings.
```

**Comment by xavisavvy** [comment]
As a note for others researching this issue, I discovered this error, and after debugging it looked like it was needing Java on my path to run. 

>> An error occurs in jsdoc process:
>> 'java' is not recognized as an internal or external command,
>> operable program or batch file.

**Comment by lauradaniela** [comment]
@xavisavvy you can resolve the problem?

**Comment by krampstudio** [comment]
@xavisavvy don't you have either an old version of the plugin ? or the deprecated package ? 
Could you post your package.json
