### ISSUE TITLE
Output to JSON?

### ISSUE THREAD

**Issue by rvangundy** [krampstudio/grunt-jsdoc#40]
The one thing I have always wanted from a doc tool is to output as a sane JSON document.  The HTML, etc. is nice, but JSON has the obvious benefit of being independent of display--so it may be formatted gracefully in to any document, formatted in to a printed book, or used for help on a command line or console interface.
##

**Comment by mboles** [comment]
I am trying to get the JSON file. I use the <code>--explain</code> flag and get the correct result without Grunt. Using Grunt and your plugin I get the standard JSDoc output, but as I said need the JSON file. I found in the cli.js file (line 388) this code where <code>--explain</code> is handled:
<pre><code>cli.processParseResults = function() {
    if (env.opts.explain) {
        cli.dumpParseResults();
    }
    else {
        cli.resolveTutorials();
        cli.generateDocs();
    }

    return cli;
};

cli.dumpParseResults = function() {
    global.dump(props.docs);

    return cli;
};</code></pre>

From that I thought I could just write the file like this using fs.writeFile:
<pre><code>cli.dumpParseResults = function() {
    var fs = require('fs');
    global.dump(props.docs);
    fs.writeFile('videojs-src/cumulative.json', props.docs);
    return cli;
};</pre></code>

The file was created, but it as empty. I tried to just write some simple text to the file <code>fs.writeFile('videojs-src/cumulative.json', 'hello');</code>, and that wouldn't write out either.

Any ideas? It seems something is interfering with the write.
Thanks-
Matt

**Comment by krampstudio** [comment]
Old issue, please reopen if needed (the plugin relies now of  the node implementation)
