### ISSUE TITLE
Support for grunt-collection

### ISSUE THREAD

**Issue by mybecks** [krampstudio/grunt-jsdoc#41]
Hello,

currently jsdoc is required in node_modules for every folder containing a Gruntfile.js and package.json.
For bigger projects there are grunt-collections where in the project root all needed modules are stored in the node_modules folder.

For now I need to have jsdoc in every subproject node_module folder, to be found from grunt-jsdoc-plugin.

BR,
mybecks

**Comment by krampstudio** [comment]
This seem to be obsolete. I never found a reference to something called `grunt-collection`
