### ISSUE TITLE
Template producing an error

### ISSUE THREAD

**Issue by filipefmelo** [krampstudio/grunt-jsdoc#55]
This is part of my grunt file:

    jsdoc : {
      dist : {
        src: [
          jsPath + 'controllers/**/*.js',
          jsPath + 'directives/**/*.js',
          jsPath + 'filters/**/*.js',
          jsPath + 'modules/**/*.js',
          jsPath + 'services/**/*.js',
          jsPath + 'app.js',
        ],
        options: {
          destination: rootPath + 'doc',
          template: 'haruki'
        }
      }
    },

When adding 

     template: 'haruki'

the error produced is as follows:

>> js: "C:/folder/folder2/folder3/server/node_modules/grunt-jsdoc/node_modules/jsdoc/jsdoc.js", line 306: exception from uncaught JavaScript throw: Error: Unable to load template: Module "haruki/publish" not found.

I'm running a Windows 7 machine.

Could someone help me out, please?

**Comment by krampstudio** [comment]
This issue should fixed now. Please reopen if you don't think so.
