### ISSUE TITLE
The input line is too long

### ISSUE THREAD

**Issue by samithaf** [krampstudio/grunt-jsdoc#59]
@krampstudio I am getting the following issue and I am on a windows 7 machine. 

> > Running "jsdoc:dist" (jsdoc) task
> > An error occurs in jsdoc process:
> > The input line is too long.
> > Warning: jsdoc failure Use --force to continue.
> > Aborted due to warnings.

I did some investigation and there was a one particular file which creates this issue on my project. Then I delete all content in the file and try to generate the document. But that did not resolve the issue. However when I add a exclude to that particular file in config, then it resolve the issue and create the documentation.

I have successfully created the documentation for same project using JSDoc Rhino version. But I am willing to integrate JSDoc creation to my grunt build process. It would be great if you can help it out.

**Comment by junedansari** [comment]
@samithaf  i have tried ur solution but not works for me.This is not taking all js file under any folder structute.
