### ISSUE TITLE
Looks like get / set operators for defining setter and getter methods is not working?

### ISSUE THREAD

**Issue by soswow** [krampstudio/grunt-jsdoc#80]
Firefox Gaia uses this task to compile documentation. It fails in places like [this](https://github.com/mozilla-b2g/gaia/blob/769b926534d2fdb3661650e43d8a96e91454896a/apps/system/js/edge_swipe_detector.js#L45-L51)
Where they have this
```javascript
  _lifecycleEnabled: false,

  get lifecycleEnabled() {
    return this._lifecycleEnabled;
  },
  set lifecycleEnabled(enable) {
    this._lifecycleEnabled = enable;
    this._updateEnabled();
  },
```
Which uses [get (mdn)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/get) and [set (mdn)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/set).

It gives
```
>> js: "/Users/soswow/Work/mozilla/gaia/apps/system/js/edge_swipe_detector.js", line 51: Property "lifecycleEnabled" already defined in this object literal.
```

**Comment by krampstudio** [comment]
It should be fixed now.
