### ISSUE TITLE
Don't make source a required argument

### ISSUE THREAD

**Issue by caseyhoward** [krampstudio/grunt-jsdoc#87]
Why do I have to provide a 'src' argument when there is already an option for a configuration file where you can specify source files? I want all my configuration in the configuration file, but I have to put this one bit of configuration in my Gruntfile.

I want to be able to either run jsdoc through grunt or on its own, but that is impossible with how grunt-jsdoc currently works. If I specify my source files in my jsdoc config file I get duplicates when I run jsdoc through grunt since it already has source files.

**Comment by krampstudio** [comment]
as from 1.1.0 also `dest` becomes optional when a config file is set.
