### ISSUE TITLE
Error when node_modules is not in the cwd - 'Warning: Arguments to path.resolve must be strings Use --force to continue.'

### ISSUE THREAD

**Issue by kaheglar** [krampstudio/grunt-jsdoc#93]
If node_module is not installed in the cwd (i.e. not the same directory as the Gruntfile) we get the error *'Warning: Arguments to path.resolve must be strings Use --force to continue.'*

Possible fix - jsdoc-plugin.js:
from
```
jsDoc = exec.lookup(grunt, jsDocNpmPath, ['node_modules/grunt-jsdoc/']);
```
to
```
jsDoc = exec.lookup(grunt, jsDocNpmPath, [__dirname + '/../']);
```

**Comment by krampstudio** [comment]
Closing for now.
