### ISSUE TITLE
Markdown support?

### ISSUE THREAD

**Issue by danielbsig** [krampstudio/grunt-jsdoc#94]
Does this library support the markdown plugin in jsDoc? If so, how is that configured in gruntfile.js?

**Comment by krampstudio** [comment]
Sorry for the late answer you can set up the markdown plugin by configuring the jsdoc.conf file as described in the [documentation](http://usejsdoc.org/plugins-markdown.html).
Then use the `configure` option in the tasks options to reference the config file.
