### ISSUE TITLE
Error occures: Commandline is to long

### ISSUE THREAD

**Issue by sateffen** [krampstudio/grunt-jsdoc#95]
Hi there,
right at the start: I'm german, so I've to translate the error freely. The original message is:
> grunt jsdoc
> Running "jsdoc:dist" (jsdoc) task
> An error occurs in jsdoc process:
> Die Befehlszeile ist zu lang.
> Warning: jsdoc failure Use --force to continue.
Translated freely it's "Commandline is to long". 

My configuration:
        jsdoc : {
            dist : {
                src: ['app/**/*.js'],
                options: {
                    destination: 'doc'
                }
            }
        }

The app folder contains around 400 js-sourcefiles, so this is a pretty small project currently. It's growing.

Other documentation systems like YUIDoc work well (but we want to use JSDoc for multible reasons), but there you'll pass in a path, not a bunch of files. Maybe you can add support for a path as well?

**Comment by krampstudio** [comment]
Closing since solutions are documented in https://github.com/krampstudio/grunt-jsdoc/issues/59
