### ISSUE TITLE
Fails to run jsdoc when _JAVA_OPTIONS is defined

### ISSUE THREAD

**Issue by thomassuckow** [krampstudio/grunt-jsdoc#99]
When _JAVA_OPTIONS is defined, Java declares the arguments to the console. This causes the plugin to abort.

```
>> An error occurs in jsdoc process:
>> Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd
Warning: jsdoc failure Use --force to continue.

Aborted due to warnings.
```

You can work around this issue by doing one of the following
* Use `--force`
* `unset _JAVA_OPTIONS`

**Comment by krampstudio** [comment]
Obsolete. Java is not needed anymore.
